/** Canonical admin portal routes — Sprint 15 */
export const adminPortalRoutes = {
  dashboard: "/admin",
  analytics: "/admin/dashboard",
  campaigns: "/admin/campaigns",
  campaignDetail: (id: string) => `/admin/campaigns/${id}`,
  settlements: "/admin/settlements",
  withdrawals: "/admin/withdrawals",
  wallets: "/admin/wallets",
  walletDetail: (userId: string) => `/admin/wallets/${userId}`,
  ledger: "/admin/ledger",
  notifications: "/admin/notifications",
  languages: "/admin/languages",
  activityLog: "/admin/activity-log",
  disputes: "/admin/disputes",
  disputeDetail: (id: string) => `/admin/disputes/${id}`,
  audit: "/admin/audit",
  featureFlags: "/admin/feature-flags",
  brands: "/admin/brands",
  projects: "/admin/projects",
  studios: "/admin/studios",
  payments: "/admin/payments",
  deposits: "/admin/deposits",
  quality: "/admin/quality",
  support: "/admin/support",
  membership: "/admin/membership",
  settings: "/admin/settings",
  system: "/admin/system",
  finance: "/admin/finance",
  monitoring: "/admin/monitoring",
  certification: "/admin/certification",
  partners: "/admin/partners",
  academy: "/admin/academy",
  showcase: "/admin/showcase",
  knowledge: "/admin/knowledge",
  knowledgeCitations: "/admin/knowledge/citations",
  knowledgeNew: "/admin/knowledge/new",
  knowledgeEdit: (id: string) => `/admin/knowledge/${id}`
} as const;
