import type { Locale } from "@/lib/i18n";

export const BRAND_CAMPAIGN_STEP2_REVIEW_COPY = {
  en: {
    headline: "AI generated 3 creative strategy routes for you",
    subtitle:
      "Each route is structured like an agency pitch deck: insight, big idea, hook, execution language, and production fit.",
    tagInsight: "Deep product insight",
    tagAudience: "Audience psychology",
    tagPlatform: "Platform algorithm fit",
    tagPerformance: "Performance forecast",
    chooseError: "Choose one creative direction or let creators submit ideas",
    creatorOptionTitle: "Do not choose these schemes",
    creatorOptionBody: "Let matched creators submit their own creative ideas after the campaign is published.",
    creatorOptionBadge: "Creator-led creative",
    creatorConfirm: "Let creators submit ideas",
    referenceNotice:
      "The following creative strategies are for reference only. Final creative direction will be confirmed jointly by the brand and creators.",
    generatingOverlay: "Generating creative schemes",
    schemeTab: "Strategy",
    reviewHint:
      "Compare strategies A/B/C above. You will only move to budget after you click the button below — payment comes one step later."
  },
  zh: {
    headline: "智能系统已为你生成 3 套创意策略",
    subtitle: "每套策略都包含消费者洞察、创意核心、开场钩子、执行语言与制作适配，结构清晰、便于比选。",
    tagInsight: "深度洞察产品卖点",
    tagAudience: "匹配受众心理",
    tagPlatform: "平台算法偏好",
    tagPerformance: "预测投放效果",
    chooseError: "请先选择一个创意方向，或选择交给创作者提交创意",
    creatorOptionTitle: "以上方案都不选",
    creatorOptionBody: "交给后续匹配到的创作者提交创意方向，品牌再从创作者方案中确认最终制作方向。",
    creatorOptionBadge: "创作者提交创意",
    creatorConfirm: "交给创作者提交创意",
    referenceNotice: "以下创意仅供参考，最终创作方向由品牌方与创作者共同确认。",
    generatingOverlay: "正在生成创意方案",
    schemeTab: "方案",
    reviewHint: "请先在上面仔细对比方案 A/B/C。只有点击下方按钮后才会进入预算设置，付款还要再下一步。"
  }
} as const;

export const BRAND_CAMPAIGN_STEP2_SCHEME_COPY = {
  en: {
    recommended: "Recommended",
    scheme: "Creative strategy",
    coreInsight: "Core insight",
    bigIdea: "Big idea",
    openingHook: "Opening hook",
    storyStructure: "Story structure",
    visualStyle: "Visual style",
    cameraLanguage: "Camera language",
    colorPalette: "Color palette",
    musicDirection: "Music direction",
    creatorRequirements: "Creator requirements",
    whyRecommended: "Why AI recommends this",
    audienceMatch: "Audience match",
    emotionalResonance: "Emotional resonance",
    productIntegration: "Product integration",
    estimatedCtr: "Estimated CTR",
    duration: "Recommended duration",
    difficulty: "AI production difficulty",
    industries: "Suitable industries",
    aiScore: "AI score",
    excellent: "Excellent",
    mediaComingSoon: "Coming soon",
    frame: "Frame",
    storyboardPreview: "Storyboard preview",
    sceneLabel: "Scene",
    audience: "Audience",
    emotion: "Emotion",
    integration: "Integration",
    aiPending: "AI pending",
    schemeCompact: "Strategy"
  },
  zh: {
    recommended: "推荐",
    scheme: "创意策略",
    coreInsight: "核心洞察",
    bigIdea: "创意核心",
    openingHook: "前三秒钩子",
    storyStructure: "故事结构",
    visualStyle: "画面风格",
    cameraLanguage: "镜头语言",
    colorPalette: "色彩方向",
    musicDirection: "音乐方向",
    creatorRequirements: "创作者要求",
    whyRecommended: "智能推荐理由",
    audienceMatch: "受众匹配",
    emotionalResonance: "情绪共鸣",
    productIntegration: "产品植入",
    estimatedCtr: "预估点击率",
    duration: "建议时长",
    difficulty: "智能制作难度",
    industries: "适合行业",
    aiScore: "智能评分",
    excellent: "优秀",
    mediaComingSoon: "即将开放",
    frame: "分镜",
    storyboardPreview: "分镜预览",
    sceneLabel: "场景",
    audience: "受众",
    emotion: "情绪",
    integration: "植入",
    aiPending: "待智能分析",
    schemeCompact: "方案"
  }
} as const;

export const BRAND_CAMPAIGN_STEP2_SIDEBAR_COPY = {
  en: {
    compare: "Creative strategy comparison",
    customCompare: "Custom comparison",
    scheme: "Strategy",
    audienceMatch: "Audience match",
    emotionalResonance: "Emotional resonance",
    productIntegration: "Product integration",
    difficulty: "AI production difficulty",
    platforms: "Suitable platforms",
    recommended: "Recommended",
    expected: "Strategy signals",
    estimatedCtr: "Estimated CTR",
    duration: "Recommended duration",
    industries: "Suitable industries",
    budget: "Estimated budget",
    export: "Export all schemes (PDF)",
    proTitle: "Unlock more creative tools",
    proBody: "Strategy preview now. Professional tools unlock after publish.",
    proUpgrade: "$30/mo · Upgrade to Professional",
    proTools: [
      { label: "AI moodboard", hint: "Visual references" },
      { label: "Color palette", hint: "Color system" },
      { label: "Camera style", hint: "Camera language" },
      { label: "Shot list", hint: "Shot breakdown" }
    ] as const
  },
  zh: {
    compare: "创意策略对比",
    customCompare: "自定义对比",
    scheme: "方案",
    audienceMatch: "受众匹配",
    emotionalResonance: "情绪共鸣",
    productIntegration: "产品植入",
    difficulty: "智能制作难度",
    platforms: "适合平台",
    recommended: "推荐",
    expected: "策略判断",
    estimatedCtr: "预估点击率",
    duration: "建议时长",
    industries: "适合行业",
    budget: "预估预算",
    export: "导出全部方案",
    proTitle: "专业版解锁更多创意工具",
    proBody: "仅展示创意策略预览，专业工具发布后开放。",
    proUpgrade: "每月 30 美元升级到专业版",
    proTools: [
      { label: "智能情绪板", hint: "参考画面与情绪板" },
      { label: "色彩方案", hint: "品牌色彩系统" },
      { label: "镜头风格", hint: "镜头语言与运镜" },
      { label: "镜头清单", hint: "分镜与镜头拆解" }
    ] as const
  }
} as const;

export const BRAND_CAMPAIGN_STEP2_PDF_DIRECTION_COPY = {
  en: {
    scheme: "Creative strategy",
    coreIdea: "Core insight",
    bigIdea: "Big idea",
    hook: "Opening hook",
    story: "Story structure",
    visual: "Visual style",
    tone: "Camera / music / color",
    shots: "Shot list",
    cta: "Call to action",
    creator: "Recommended creator type",
    outcome: "Expected performance",
    rationale: "Why AI recommends this",
    audienceMatch: "Audience match",
    emotionalResonance: "Emotional resonance",
    productIntegration: "Product integration",
    estimatedCtr: "Estimated CTR",
    duration: "Recommended duration"
  },
  zh: {
    scheme: "创意策略",
    coreIdea: "核心洞察",
    bigIdea: "创意核心",
    hook: "前三秒钩子",
    story: "故事结构",
    visual: "画面风格",
    tone: "镜头 / 音乐 / 色彩",
    shots: "镜头建议",
    cta: "行动号召",
    creator: "推荐创作者类型",
    outcome: "预期表现",
    rationale: "智能推荐理由",
    audienceMatch: "受众匹配",
    emotionalResonance: "情绪共鸣",
    productIntegration: "产品植入",
    estimatedCtr: "预估点击率",
    duration: "建议时长"
  }
} as const;

export const BRAND_CAMPAIGN_STEP2_PDF_DOC_COPY = {
  en: {
    docTitle: "VINCIS creative strategy export",
    overview: "1. Filled brief",
    production: "2. Production & delivery settings",
    references: "3. Assets & references",
    schemes: "4. All creative strategy routes",
    selected: "Selected scheme",
    generated: "Exported at",
    projectName: "Project name",
    oneLiner: "Ad one-liner",
    industry: "Industry",
    brand: "Brand name",
    website: "Brand website",
    brief: "Detailed brief",
    style: "Style preference",
    include: "Must include",
    avoid: "Must avoid",
    duration: "Video duration",
    aspect: "Aspect ratio",
    resolution: "Resolution",
    fps: "Frame rate",
    quantity: "Video quantity",
    budget: "Selected budget",
    timeline: "Timeline",
    dates: "Schedule",
    platforms: "Platforms",
    refs: "Reference links / videos",
    closePreview: "Close preview",
    closeFallback: "If the window does not close, close this tab directly."
  },
  zh: {
    docTitle: "VINCIS 创意策略导出",
    overview: "一、已填写需求",
    production: "二、制作与交付设置",
    references: "三、素材与参考",
    schemes: "四、全部创意策略",
    selected: "当前选择方案",
    generated: "导出时间",
    projectName: "项目名称",
    oneLiner: "广告一句话",
    industry: "所属行业",
    brand: "品牌名称",
    website: "品牌官网",
    brief: "详细需求",
    style: "风格偏好",
    include: "必须包含",
    avoid: "需要避免",
    duration: "视频时长",
    aspect: "视频比例",
    resolution: "分辨率",
    fps: "帧率",
    quantity: "视频数量",
    budget: "已选预算",
    timeline: "预计周期",
    dates: "时间安排",
    platforms: "投放平台",
    refs: "参考链接 / 参考视频",
    closePreview: "关闭预览",
    closeFallback: "如果窗口没有关闭，请直接关闭当前标签页。"
  }
} as const;

export function brandCampaignStep2Copy(locale: Locale) {
  return {
    review: BRAND_CAMPAIGN_STEP2_REVIEW_COPY[locale],
    scheme: BRAND_CAMPAIGN_STEP2_SCHEME_COPY[locale],
    sidebar: BRAND_CAMPAIGN_STEP2_SIDEBAR_COPY[locale],
    pdfDirection: BRAND_CAMPAIGN_STEP2_PDF_DIRECTION_COPY[locale],
    pdfDoc: BRAND_CAMPAIGN_STEP2_PDF_DOC_COPY[locale]
  };
}
