-- Seedance IMAGE_TO_VIDEO fallback rules (reference / library assets).
-- Runtime credits still come from seedance-credits-pricing.ts; these anchor DB integrity checks.

INSERT INTO "credit_pricing_rules" (
  "id", "ai_model_id", "provider", "model", "generation_type", "mode", "label",
  "duration_sec", "resolution", "output_count", "provider_cost_minor",
  "credit_price", "margin_percent", "refund_on_failure", "minimum_balance",
  "enabled", "status", "version", "published_at", "sort_order", "updated_at"
)
VALUES
  (
    'rule_seedance2_i2v_default',
    'aim_seedance2',
    'ByteDance',
    'seedance-2.0',
    'VIDEO',
    'IMAGE_TO_VIDEO',
    'Seedance 2.0 · Image to video · default (+15%)',
    NULL,
    NULL,
    1,
    60,
    69,
    13,
    true,
    0,
    true,
    'PUBLISHED',
    1,
    CURRENT_TIMESTAMP,
    7,
    CURRENT_TIMESTAMP
  ),
  (
    'rule_seedance2_fast_i2v_default',
    'aim_seedance2_fast',
    'ByteDance',
    'seedance-2.0-fast',
    'VIDEO',
    'IMAGE_TO_VIDEO',
    'Seedance 2.0 Fast · Image to video · default (+15%)',
    NULL,
    NULL,
    1,
    50,
    58,
    13,
    true,
    0,
    true,
    'PUBLISHED',
    1,
    CURRENT_TIMESTAMP,
    8,
    CURRENT_TIMESTAMP
  ),
  (
    'rule_seedance2_mini_i2v_default',
    'aim_seedance2_mini',
    'ByteDance',
    'seedance-2.0-mini',
    'VIDEO',
    'IMAGE_TO_VIDEO',
    'Seedance 2.0 Mini · Image to video · default (+15%)',
    NULL,
    NULL,
    1,
    30,
    35,
    13,
    true,
    0,
    true,
    'PUBLISHED',
    1,
    CURRENT_TIMESTAMP,
    9,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO UPDATE SET
  "mode" = EXCLUDED."mode",
  "label" = EXCLUDED."label",
  "provider_cost_minor" = EXCLUDED."provider_cost_minor",
  "credit_price" = EXCLUDED."credit_price",
  "margin_percent" = EXCLUDED."margin_percent",
  "enabled" = EXCLUDED."enabled",
  "status" = EXCLUDED."status",
  "published_at" = COALESCE("credit_pricing_rules"."published_at", EXCLUDED."published_at"),
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = EXCLUDED."updated_at";
