ALTER TYPE "AnnotationType" ADD VALUE IF NOT EXISTS 'PEN';
ALTER TYPE "AnnotationType" ADD VALUE IF NOT EXISTS 'TEXT';

ALTER TABLE "review_annotations"
ADD COLUMN IF NOT EXISTS "data_json" JSONB,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3);
